name: build-blaze
options:
  bundleIdPrefix: com.example
  developmentLanguage: en
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.example.buildblaze
    PRODUCT_NAME: build-blaze
    SWIFT_VERSION: 5
    MARKETING_VERSION: 1
    CURRENT_PROJECT_VERSION: 1
    SUPPORTED_PLATFORMS: iphoneos iphonesimulator
    TARGETED_DEVICE_FAMILY: '1'
    SUPPORTS_MACCATALYST: 'NO'
    ALWAYS_SEARCH_USER_PATHS: 'NO'
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
targets:
  build-blaze:
    type: application
    platform: iOS
    deploymentTarget: '17.0'
    sources:
      - path: build-blaze
    info:
      path: build-blaze/Info.plist
      properties:
        CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        CFBundleDisplayName: $(PRODUCT_NAME)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: 6
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleIconName: AppIcon
        ITSAppUsesNonExemptEncryption: false
        LSRequiresIPhoneOS: true
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchStoryboardName: LaunchScreen
        UIRequiredDeviceCapabilities:
          - arm64
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    dependencies:
      - package: supabase-swift
        product: Auth
      - package: supabase-swift
        product: PostgREST
      - package: supabase-swift
        product: Supabase
schemes:
  build-blaze:
    build:
      targets:
        build-blaze: all
    run:
      config: Debug
    archive:
      config: Release
packages:
  supabase-swift:
    url: https://github.com/supabase/supabase-swift
    from: 2.0.0
